package restaurantmanagement;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Connect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit
 */
public class changeprice extends javax.swing.JFrame {

    /**
     * Creates new form changeprice
     */
    public changeprice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        c4 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        b8 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        a9 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b10 = new javax.swing.JTextField();
        b9 = new javax.swing.JTextField();
        c9 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        c2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1347, 713));
        setMinimumSize(new java.awt.Dimension(1347, 713));
        setPreferredSize(new java.awt.Dimension(1347, 713));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/I.jpg"))); // NOI18N
        jLabel2.setText("Change Price");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 0, 1510, 70);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BURGERS");

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Double tikki");

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Single tikki");

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cheese buger");

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Grilled burger");

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pizzas");

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cheese pizza");

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tomato pizza");

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Spegati pizza");

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Onion pizza");

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Drinks and others");

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Coke");

        jLabel14.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("French fries");

        jLabel15.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cake");

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Chocolate shake");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 280, 650);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel17.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("click to change");

        jLabel18.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Current value");

        jLabel19.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Changed value");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 60, 880, 40);

        a4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a4);
        a4.setBounds(310, 240, 290, 30);

        a1.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a1);
        a1.setBounds(310, 120, 290, 30);

        a2.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a2);
        a2.setBounds(310, 160, 290, 30);

        a3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a3);
        a3.setBounds(310, 200, 290, 30);

        b1.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b1);
        b1.setBounds(650, 120, 290, 30);

        b2.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b2);
        b2.setBounds(650, 160, 290, 30);

        b3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b3);
        b3.setBounds(650, 200, 290, 30);

        b4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b4);
        b4.setBounds(650, 240, 290, 30);

        c4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c4.setText("Change");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(990, 240, 160, 30);

        c1.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c1.setText("Change");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(990, 120, 160, 30);

        c3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c3.setText("Change");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(990, 200, 160, 30);

        a5.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a5);
        a5.setBounds(310, 310, 290, 30);

        a6.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a6);
        a6.setBounds(310, 350, 290, 30);

        a7.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a7);
        a7.setBounds(310, 390, 290, 30);

        a8.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a8);
        a8.setBounds(310, 430, 290, 30);

        b8.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b8);
        b8.setBounds(650, 430, 290, 30);

        b7.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b7);
        b7.setBounds(650, 390, 290, 30);

        b6.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b6);
        b6.setBounds(650, 350, 290, 30);

        b5.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b5);
        b5.setBounds(650, 310, 290, 30);

        c5.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c5.setText("Change");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(990, 310, 170, 30);

        c6.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c6.setText("Change");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(990, 350, 170, 30);

        c7.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c7.setText("Change");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(990, 390, 170, 30);

        c8.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c8.setText("Change");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        getContentPane().add(c8);
        c8.setBounds(990, 420, 170, 30);

        a9.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a9);
        a9.setBounds(310, 500, 290, 30);

        a10.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a10);
        a10.setBounds(310, 540, 290, 30);

        a11.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a11);
        a11.setBounds(310, 580, 290, 30);

        a12.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        a12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(a12);
        a12.setBounds(310, 620, 290, 30);

        b12.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b12);
        b12.setBounds(650, 620, 290, 30);

        b11.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b11);
        b11.setBounds(650, 580, 290, 30);

        b10.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b10);
        b10.setBounds(650, 540, 290, 30);

        b9.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        b9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b9);
        b9.setBounds(650, 500, 290, 30);

        c9.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c9.setText("Change");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        getContentPane().add(c9);
        c9.setBounds(990, 500, 170, 30);

        c10.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c10.setText("Change");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(990, 540, 170, 30);

        c11.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c11.setText("Change");
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        getContentPane().add(c11);
        c11.setBounds(990, 580, 170, 30);

        c12.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c12.setText("Change");
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        getContentPane().add(c12);
        c12.setBounds(990, 620, 170, 30);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-heading-icons_home.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1210, 0, 128, 90);

        jLabel21.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("LOG OUT");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1210, 90, 130, 40);

        c2.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        c2.setText("Change");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(990, 160, 160, 30);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aurora_burst_3.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 1350, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new adminlogin().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
          new adminlogin().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel20MouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
       
       Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set SINGLETIKKI=("+b1.getText()+")  where SINGLETIKKI=("+a1.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
   
    }//GEN-LAST:event_c1ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set ONIONPI=("+b8.getText()+")  where ONIONPI=("+a8.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c8ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
        Statement st=new Connect().createConnection();
      ResultSet rs=st.executeQuery("select * FROM MENU");
      rs.next();
      a1.setText(String.valueOf(rs.getInt("SINGLETIKKI")));
      a2.setText(String.valueOf(rs.getInt("DOUBLETIKKI")));
      a3.setText(String.valueOf(rs.getInt("CHEESEBUR")));
      a4.setText(String.valueOf(rs.getInt("GRILLEDBUR")));
      a5.setText(String.valueOf(rs.getInt("CHEESEPI")));
      a6.setText(String.valueOf(rs.getInt("TOMATOPI")));
      a7.setText(String.valueOf(rs.getInt("SPEGATIPI")));
      a8.setText(String.valueOf(rs.getInt("ONIONPI")));
      a9.setText(String.valueOf(rs.getInt("COKE")));
      a10.setText(String.valueOf(rs.getInt("FRIES")));
      a11.setText(String.valueOf(rs.getInt("CAKE")));
      a12.setText(String.valueOf(rs.getInt("SHAKE")));
      
      } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_formWindowActivated
    }
    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
         Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set DOUBLETIKKI=("+b2.getText()+")  where DOUBLETIKKI=("+a2.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
         Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set CHEESEBUR=("+b3.getText()+")  where CHEESEBUR=("+a3.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set GRILLEDBUR=("+b4.getText()+")  where GRILLEDBUR=("+a4.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set CHEESEPI=("+b5.getText()+")  where CHEESEPI=("+a5.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set TOMATOPI=("+b6.getText()+")  where TOMATOPI=("+a6.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set SPEGATIPI=("+b7.getText()+")  where SPEGATIPI=("+a7.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
         
    }//GEN-LAST:event_c7ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
         Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set COKE=("+b9.getText()+")  where COKE=("+a9.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
       Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set FRIES=("+b10.getText()+")  where FRIES=("+a10.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }  // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set CAKE=("+b11.getText()+")  where CAKE=("+a11.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        } // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
         Statement st=new Connect().createConnection();
        try {
       st.executeUpdate("update MENU set SHAKE=("+b12.getText()+")  where SHAKE=("+a12.getText()+")");
         JOptionPane.showMessageDialog(null, "VALUE CHANGED SUCCESSFULLY!!");
        } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
      
        }
    }//GEN-LAST:event_c12ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeprice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b10;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b6;
    private javax.swing.JTextField b7;
    private javax.swing.JTextField b8;
    private javax.swing.JTextField b9;
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c11;
    private javax.swing.JButton c12;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
