package restaurantmanagement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Connect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    public void bill(){ 
 String bf=txt.getText();
        int a=Integer.parseInt(txt.getText());
        int ad=a+1;
        String af=String.valueOf(ad); 
        System.out.println(af);
     try{
       Class.forName("org.apache.derby.jdbc.ClientDriver");
       Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/RESTAURANT","ankit","ankit");
       PreparedStatement pst=con.prepareStatement("Update INVOICE set ID=('"+af+"') where ID=('"+bf+"')");
       pst.executeUpdate();
       }
       catch(Exception e){
           System.out.println(e);
       }
       
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel86 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel87 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel88 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jLabel89 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel78 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel81 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel73 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        lb15 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel82 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        a6 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        lb6 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        jSpinner14 = new javax.swing.JSpinner();
        jLabel85 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        jPanel29 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        burgertotal = new javax.swing.JLabel();
        pizzatotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        drinkstotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        homedelivery = new javax.swing.JCheckBox();
        clear_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        calculate_bill_btn = new javax.swing.JButton();
        jLabel80 = new javax.swing.JLabel();
        place_order_btn = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1369, 804));
        setMinimumSize(new java.awt.Dimension(1369, 804));
        setPreferredSize(new java.awt.Dimension(1369, 804));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button-icon-png-15.jpg"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 0, 90, 80);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/I.jpg"))); // NOI18N
        jLabel2.setText("    Restaurant Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 80);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Others");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(0, 100, 170, 50);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Drinks");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(0, 0, 170, 60);

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("and");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(0, 50, 170, 60);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 170, 150);

        jPanel24.setBackground(new java.awt.Color(255, 204, 153));
        jPanel24.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel24.setLayout(null);

        jLabel59.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Coke");
        jPanel24.add(jLabel59);
        jLabel59.setBounds(0, 0, 190, 26);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coke.jpg"))); // NOI18N
        jPanel24.add(jLabel60);
        jLabel60.setBounds(0, 30, 170, 80);

        jLabel61.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel61.setText("Rs.");
        jPanel24.add(jLabel61);
        jLabel61.setBounds(13, 112, 60, 40);

        a9.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a9.setText("Unkown");
        jPanel24.add(a9);
        a9.setBounds(40, 110, 90, 40);

        lb9.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jPanel24.add(lb9);
        lb9.setBounds(130, 110, 60, 40);

        jSpinner9.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner9.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin9(evt);
            }
        });
        jPanel24.add(jSpinner9);
        jSpinner9.setBounds(168, 25, 20, 90);

        jLabel86.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("x");
        jPanel24.add(jLabel86);
        jLabel86.setBounds(100, 110, 30, 40);

        jPanel1.add(jPanel24);
        jPanel24.setBounds(170, 0, 190, 150);

        jPanel25.setBackground(new java.awt.Color(255, 204, 153));
        jPanel25.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel25.setLayout(null);

        jLabel64.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("French fries");
        jPanel25.add(jLabel64);
        jLabel64.setBounds(0, 0, 190, 26);

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/french fries.jpg"))); // NOI18N
        jPanel25.add(jLabel65);
        jLabel65.setBounds(0, 30, 170, 80);

        jLabel66.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel66.setText("Rs.");
        jPanel25.add(jLabel66);
        jLabel66.setBounds(13, 112, 60, 40);

        a10.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a10.setText("Unkown");
        jPanel25.add(a10);
        a10.setBounds(40, 110, 90, 40);

        lb10.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel25.add(lb10);
        lb10.setBounds(130, 110, 60, 40);

        jSpinner10.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner10.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin10(evt);
            }
        });
        jPanel25.add(jSpinner10);
        jSpinner10.setBounds(168, 25, 20, 90);

        jLabel87.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel87.setText("x");
        jPanel25.add(jLabel87);
        jLabel87.setBounds(110, 110, 30, 40);

        jPanel1.add(jPanel25);
        jPanel25.setBounds(360, 0, 190, 150);

        jPanel26.setBackground(new java.awt.Color(255, 204, 153));
        jPanel26.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel26.setLayout(null);

        jLabel69.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Cake");
        jPanel26.add(jLabel69);
        jLabel69.setBounds(0, 0, 210, 26);

        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cake.jpg"))); // NOI18N
        jPanel26.add(jLabel70);
        jLabel70.setBounds(0, 30, 190, 80);

        jLabel71.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel71.setText("Rs.");
        jPanel26.add(jLabel71);
        jLabel71.setBounds(10, 110, 40, 40);

        a11.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a11.setText("Unkown");
        jPanel26.add(a11);
        a11.setBounds(40, 110, 90, 40);

        lb11.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel26.add(lb11);
        lb11.setBounds(130, 110, 80, 40);

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner11.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin11(evt);
            }
        });
        jPanel26.add(jSpinner11);
        jSpinner11.setBounds(190, 30, 20, 80);

        jLabel88.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel88.setText("x");
        jPanel26.add(jLabel88);
        jLabel88.setBounds(110, 110, 30, 40);

        jPanel1.add(jPanel26);
        jPanel26.setBounds(550, 0, 210, 150);

        jPanel27.setBackground(new java.awt.Color(255, 204, 153));
        jPanel27.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel27.setLayout(null);

        jLabel74.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Chocolate shake");
        jPanel27.add(jLabel74);
        jLabel74.setBounds(0, 0, 210, 26);

        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choco shake.jpg"))); // NOI18N
        jPanel27.add(jLabel75);
        jLabel75.setBounds(0, 30, 190, 80);

        jLabel76.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel76.setText("Rs.");
        jPanel27.add(jLabel76);
        jLabel76.setBounds(13, 112, 50, 40);

        a12.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a12.setText("Unkown");
        jPanel27.add(a12);
        a12.setBounds(40, 110, 80, 40);

        lb12.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel27.add(lb12);
        lb12.setBounds(130, 110, 80, 40);

        jSpinner12.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner12.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin12(evt);
            }
        });
        jPanel27.add(jSpinner12);
        jSpinner12.setBounds(190, 30, 20, 80);

        jLabel89.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel89.setText("x");
        jPanel27.add(jLabel89);
        jLabel89.setBounds(110, 110, 40, 40);

        jPanel1.add(jPanel27);
        jPanel27.setBounds(760, 0, 210, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 360, 970, 150);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 204, 153));
        jLabel3.setFont(new java.awt.Font("Georgia", 3, 32)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Burgers");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 170, 140);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 170, 140);

        jPanel8.setBackground(new java.awt.Color(255, 204, 153));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel8.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Cheese burger");
        jPanel8.add(jLabel29);
        jLabel29.setBounds(0, 0, 190, 26);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cheese.jpg"))); // NOI18N
        jPanel8.add(jLabel30);
        jLabel30.setBounds(0, 30, 190, 80);

        jLabel31.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel31.setText("Rs.");
        jPanel8.add(jLabel31);
        jLabel31.setBounds(13, 112, 40, 26);

        a3.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a3.setText("Unkown");
        jPanel8.add(a3);
        a3.setBounds(40, 110, 90, 30);

        lb3.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel8.add(lb3);
        lb3.setBounds(130, 110, 80, 26);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner3.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin3(evt);
            }
        });
        jPanel8.add(jSpinner3);
        jSpinner3.setBounds(190, 30, 20, 80);

        jLabel78.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("x");
        jPanel8.add(jLabel78);
        jLabel78.setBounds(100, 110, 30, 30);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(550, 0, 210, 140);

        jPanel9.setBackground(new java.awt.Color(255, 204, 153));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel9.setLayout(null);

        lb1.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel9.add(lb1);
        lb1.setBounds(130, 110, 60, 26);

        jLabel21.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Single tikki");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(0, 0, 190, 26);

        a1.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a1.setText("Unkown");
        jPanel9.add(a1);
        a1.setBounds(40, 110, 80, 30);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin1(evt);
            }
        });
        jPanel9.add(jSpinner1);
        jSpinner1.setBounds(170, 30, 20, 80);

        jLabel23.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel23.setText("Rs.");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(13, 112, 40, 26);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/single alo.jpg"))); // NOI18N
        jPanel9.add(jLabel24);
        jLabel24.setBounds(0, 30, 170, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(100, 110, 30, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(170, 0, 190, 140);

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel11.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Grilled burger");
        jPanel11.add(jLabel34);
        jLabel34.setBounds(0, 0, 210, 26);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grill  burger.jpg"))); // NOI18N
        jPanel11.add(jLabel35);
        jLabel35.setBounds(0, 30, 190, 80);

        jLabel36.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel36.setText("Rs.");
        jPanel11.add(jLabel36);
        jLabel36.setBounds(13, 112, 60, 26);

        a4.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a4.setText("Unkown");
        jPanel11.add(a4);
        a4.setBounds(40, 110, 80, 30);

        lb4.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel11.add(lb4);
        lb4.setBounds(140, 110, 70, 26);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner4.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin4(evt);
            }
        });
        jPanel11.add(jSpinner4);
        jSpinner4.setBounds(190, 30, 20, 80);

        jLabel81.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel81.setText("x");
        jPanel11.add(jLabel81);
        jLabel81.setBounds(120, 110, 30, 30);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(760, 0, 210, 140);

        jPanel12.setBackground(new java.awt.Color(255, 204, 153));
        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel12.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Double tikki");
        jPanel12.add(jLabel25);
        jLabel25.setBounds(0, 0, 190, 26);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/double aloo.jpg"))); // NOI18N
        jPanel12.add(jLabel26);
        jLabel26.setBounds(0, 30, 170, 80);

        jLabel27.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel27.setText("Rs.");
        jPanel12.add(jLabel27);
        jLabel27.setBounds(13, 112, 50, 26);

        a2.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a2.setText("Unkown");
        jPanel12.add(a2);
        a2.setBounds(40, 110, 90, 30);

        lb2.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel12.add(lb2);
        lb2.setBounds(130, 110, 60, 26);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner2.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin2(evt);
            }
        });
        jPanel12.add(jSpinner2);
        jSpinner2.setBounds(170, 30, 20, 80);

        jLabel73.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel73.setText("x");
        jPanel12.add(jLabel73);
        jLabel73.setBounds(110, 110, 30, 30);

        jPanel3.add(jPanel12);
        jPanel12.setBounds(360, 0, 190, 140);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 970, 140);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 255, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel6.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 204, 153));
        jLabel5.setFont(new java.awt.Font("Georgia", 3, 32)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pizzas");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(0, 0, 170, 140);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 170, 140);

        jPanel15.setBackground(new java.awt.Color(255, 204, 153));
        jPanel15.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel15.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Spegati pizza");
        jPanel15.add(jLabel49);
        jLabel49.setBounds(0, 0, 200, 26);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spegathi.jpg"))); // NOI18N
        jPanel15.add(jLabel50);
        jLabel50.setBounds(0, 30, 190, 80);

        jLabel51.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel51.setText("Rs.");
        jPanel15.add(jLabel51);
        jLabel51.setBounds(13, 112, 50, 26);

        a7.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a7.setText("Unkown");
        jPanel15.add(a7);
        a7.setBounds(50, 110, 90, 30);

        lb7.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel15.add(lb7);
        lb7.setBounds(140, 110, 70, 30);

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner7.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin7(evt);
            }
        });
        jPanel15.add(jSpinner7);
        jSpinner7.setBounds(190, 30, 20, 80);

        lb15.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lb15.setText("x");
        jPanel15.add(lb15);
        lb15.setBounds(120, 110, 30, 25);

        jPanel4.add(jPanel15);
        jPanel15.setBounds(550, 0, 210, 140);

        jPanel18.setBackground(new java.awt.Color(255, 204, 153));
        jPanel18.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel18.setLayout(null);

        jLabel39.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Cheese pizza");
        jPanel18.add(jLabel39);
        jLabel39.setBounds(0, 0, 190, 26);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chesse pizza.jpg"))); // NOI18N
        jPanel18.add(jLabel40);
        jLabel40.setBounds(0, 30, 170, 80);

        jLabel41.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel41.setText("Rs.");
        jPanel18.add(jLabel41);
        jLabel41.setBounds(13, 112, 50, 26);

        a5.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a5.setText("Unkown");
        jPanel18.add(a5);
        a5.setBounds(40, 110, 90, 30);

        lb5.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel18.add(lb5);
        lb5.setBounds(130, 110, 60, 30);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner5.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin5(evt);
            }
        });
        jPanel18.add(jSpinner5);
        jSpinner5.setBounds(168, 25, 20, 90);

        jLabel82.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel82.setText("x");
        jPanel18.add(jLabel82);
        jLabel82.setBounds(110, 110, 30, 30);

        jPanel4.add(jPanel18);
        jPanel18.setBounds(170, 0, 190, 140);

        jPanel10.setBackground(new java.awt.Color(255, 204, 153));
        jPanel10.setLayout(null);

        a6.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a6.setText("Unkown");
        jPanel10.add(a6);
        a6.setBounds(40, 110, 72, 30);

        jLabel38.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel38.setText("Rs.");
        jPanel10.add(jLabel38);
        jLabel38.setBounds(3, 112, 60, 26);

        jLabel43.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Tomato pizza");
        jPanel10.add(jLabel43);
        jLabel43.setBounds(0, 0, 190, 26);

        jSpinner13.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner13.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin6(evt);
            }
        });
        jPanel10.add(jSpinner13);
        jSpinner13.setBounds(168, 25, 20, 80);

        lb6.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel10.add(lb6);
        lb6.setBounds(130, 109, 60, 30);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/toamto.jpg"))); // NOI18N
        jPanel10.add(jLabel48);
        jLabel48.setBounds(0, 30, 170, 80);

        jLabel83.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel83.setText("x");
        jPanel10.add(jLabel83);
        jLabel83.setBounds(110, 110, 30, 30);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(360, 0, 190, 140);

        jPanel13.setBackground(new java.awt.Color(255, 204, 153));
        jPanel13.setLayout(null);

        jLabel53.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Onion pizza");
        jPanel13.add(jLabel53);
        jLabel53.setBounds(0, 0, 210, 26);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onion cap.jpg"))); // NOI18N
        jPanel13.add(jLabel58);
        jLabel58.setBounds(0, 30, 190, 80);

        a8.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        a8.setText("Unkown");
        jPanel13.add(a8);
        a8.setBounds(40, 110, 80, 30);

        jLabel68.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jLabel68.setText("Rs.");
        jPanel13.add(jLabel68);
        jLabel68.setBounds(13, 112, 50, 26);

        lb8.setFont(new java.awt.Font("Verdana", 3, 16)); // NOI18N
        jPanel13.add(lb8);
        lb8.setBounds(130, 110, 80, 26);

        jSpinner14.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner14.setPreferredSize(new java.awt.Dimension(28, 20));
        jSpinner14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin8(evt);
            }
        });
        jPanel13.add(jSpinner14);
        jSpinner14.setBounds(190, 30, 20, 80);

        jLabel85.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel85.setText("x");
        jPanel13.add(jLabel85);
        jLabel85.setBounds(110, 110, 30, 30);

        jPanel4.add(jPanel13);
        jPanel13.setBounds(760, 0, 210, 140);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 220, 970, 140);

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        bill.setColumns(20);
        bill.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(980, 80, 370, 370);

        jPanel29.setBackground(new java.awt.Color(204, 255, 204));
        jPanel29.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BURGERS TOTAL");

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PIZZAS TOTAL");

        burgertotal.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        burgertotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pizzatotal.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        pizzatotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DRINKS AND OTHERS");

        drinkstotal.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        drinkstotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TOTAL");

        total.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        gst.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        gst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("GST TAX");

        jLabel19.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("GRAND TOTAL");

        grandtotal.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        grandtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        homedelivery.setBackground(new java.awt.Color(204, 255, 204));
        homedelivery.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        homedelivery.setText("Home Delivery");

        clear_btn.setBackground(new java.awt.Color(255, 255, 255));
        clear_btn.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(0, 0, 204));
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pizzatotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(burgertotal, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(drinkstotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homedelivery))
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grandtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(burgertotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pizzatotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel29Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(homedelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );

        getContentPane().add(jPanel29);
        jPanel29.setBounds(0, 450, 970, 290);

        exit_btn.setBackground(new java.awt.Color(255, 255, 255));
        exit_btn.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(0, 0, 204));
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn);
        exit_btn.setBounds(1120, 10, 130, 60);

        calculate_bill_btn.setBackground(new java.awt.Color(255, 255, 255));
        calculate_bill_btn.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        calculate_bill_btn.setForeground(new java.awt.Color(0, 0, 204));
        calculate_bill_btn.setText("Calculate");
        calculate_bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_bill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(calculate_bill_btn);
        calculate_bill_btn.setBounds(1060, 480, 200, 70);
        getContentPane().add(jLabel80);
        jLabel80.setBounds(610, 0, 50, 80);

        place_order_btn.setBackground(new java.awt.Color(255, 255, 255));
        place_order_btn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        place_order_btn.setForeground(new java.awt.Color(0, 0, 255));
        place_order_btn.setText("Place order");
        place_order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_order_btnActionPerformed(evt);
            }
        });
        getContentPane().add(place_order_btn);
        place_order_btn.setBounds(1060, 600, 200, 60);

        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setIcon(new javax.swing.ImageIcon("D:\\Pictures\\apple-mac-high-resolution-wallpaper-1.png")); // NOI18N
        getContentPane().add(jLabel79);
        jLabel79.setBounds(0, -10, 1380, 740);
        getContentPane().add(txt);
        txt.setBounds(0, 0, 0, 0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void spin1(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin1
        // TODO add your handling code here:
         String spinner="";
        Integer myInt=(Integer) jSpinner1.getValue();
        spinner=myInt.toString();
        lb1.setText(spinner);
        
    }//GEN-LAST:event_spin1

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
lb1.setText("0");
lb2.setText("0");
lb3.setText("0");
lb4.setText("0");
lb5.setText("0");
lb6.setText("0");
lb7.setText("0");
lb8.setText("0");
lb9.setText("0");
lb10.setText("0");
lb11.setText("0");
lb12.setText("0");
    try {
        Statement st=new Connect().createConnection();
      ResultSet rs=st.executeQuery("select * FROM MENU");
      rs.next();
      a1.setText(String.valueOf(rs.getInt("SINGLETIKKI")));
      a2.setText(String.valueOf(rs.getInt("DOUBLETIKKI")));
      a3.setText(String.valueOf(rs.getInt("CHEESEBUR")));
      a4.setText(String.valueOf(rs.getInt("GRILLEDBUR")));
      a5.setText(String.valueOf(rs.getInt("CHEESEPI")));
      a6.setText(String.valueOf(rs.getInt("TOMATOPI")));
      a7.setText(String.valueOf(rs.getInt("SPEGATIPI")));
      a8.setText(String.valueOf(rs.getInt("ONIONPI")));
      a9.setText(String.valueOf(rs.getInt("COKE")));
      a10.setText(String.valueOf(rs.getInt("FRIES")));
      a11.setText(String.valueOf(rs.getInt("CAKE")));
      a12.setText(String.valueOf(rs.getInt("SHAKE")));
      
      } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
    }   
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void spin2(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin2
       String spinner="";
        Integer myInt=(Integer) jSpinner2.getValue();
        spinner=myInt.toString();
        lb2.setText(spinner);
    }//GEN-LAST:event_spin2

    private void spin3(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin3
         String spinner="";
        Integer myInt=(Integer) jSpinner3.getValue();
        spinner=myInt.toString();
        lb3.setText(spinner);
    }//GEN-LAST:event_spin3

    private void spin4(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin4
        // TODO add your handling code here:
          String spinner="";
        Integer myInt=(Integer) jSpinner4.getValue();
        spinner=myInt.toString();
        lb4.setText(spinner);
    }//GEN-LAST:event_spin4

    private void spin5(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin5
        // TODO add your handling code here:
          String spinner="";
        Integer myInt=(Integer) jSpinner5.getValue();
        spinner=myInt.toString();
        lb5.setText(spinner);
    }//GEN-LAST:event_spin5

    private void spin6(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin6
        // TODO add your handling code here:
          String spinner="";
        Integer myInt=(Integer) jSpinner13.getValue();
        spinner=myInt.toString();
        lb6.setText(spinner);
    }//GEN-LAST:event_spin6

    private void spin7(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin7
        // TODO add your handling code here:
          String spinner="";
        Integer myInt=(Integer) jSpinner7.getValue();
        spinner=myInt.toString();
        lb7.setText(spinner);
    }//GEN-LAST:event_spin7

    private void spin8(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin8
        // TODO add your handling code here:
          String spinner="";
        Integer myInt=(Integer) jSpinner14.getValue();
        spinner=myInt.toString();
        lb8.setText(spinner);
    }//GEN-LAST:event_spin8

    private void spin9(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin9
        // TODO add your handling code here:
        String spinner="";
        Integer myInt=(Integer) jSpinner9.getValue();
        spinner=myInt.toString();
        lb9.setText(spinner);
        
    }//GEN-LAST:event_spin9

    private void spin10(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin10
        // TODO add your handling code here:
        String spinner="";
        Integer myInt=(Integer) jSpinner10.getValue();
        spinner=myInt.toString();
        lb10.setText(spinner);
    }//GEN-LAST:event_spin10

    private void spin11(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin11
        // TODO add your handling code here:
        String spinner="";
        Integer myInt=(Integer) jSpinner11.getValue();
        spinner=myInt.toString();
        lb11.setText(spinner);
    }//GEN-LAST:event_spin11

    private void spin12(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin12
        // TODO add your handling code here:
        String spinner="";
        Integer myInt=(Integer) jSpinner12.getValue();
        spinner=myInt.toString();
        lb12.setText(spinner);
    }//GEN-LAST:event_spin12

    private void calculate_bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_bill_btnActionPerformed
        // TODO add your handling code here:
       try {
        Statement st=new Connect().createConnection();
      ResultSet rs=st.executeQuery("select * FROM MENU");
      rs.next();
      int singletikki=rs.getInt("SINGLETIKKI");
      int doubletikki=rs.getInt("DOUBLETIKKI");
      int cheesebur=rs.getInt("CHEESEBUR");
      int grilledbur=rs.getInt("GRILLEDBUR");
      int cheesepi=rs.getInt("CHEESEPI");
      int tomatopi=rs.getInt("TOMATOPI");
      int spegati=rs.getInt("SPEGATIPI");
      int onionpi=rs.getInt("ONIONPI");
      int cokes=rs.getInt("COKE");
      int frie=rs.getInt("FRIES");
      int cakes=rs.getInt("CAKE");
      int shakes=rs.getInt("SHAKE");
 
             //getting values from jspinners
 int spin1=Integer.parseInt(lb1.getText());
 int spin2=Integer.parseInt(lb2.getText());
 int spin3=Integer.parseInt(lb3.getText());
 int spin4=Integer.parseInt(lb4.getText());
 int spin5=Integer.parseInt(lb5.getText());
 int spin6=Integer.parseInt(lb6.getText());
 int spin7=Integer.parseInt(lb7.getText());
 int spin8=Integer.parseInt(lb8.getText());
 int spin9=Integer.parseInt(lb9.getText());
 int spin10=Integer.parseInt(lb10.getText());
 int spin11=Integer.parseInt(lb11.getText());
 int spin12=Integer.parseInt(lb12.getText());
 
 //calculating values
 
 int stikki=singletikki*spin1;
 int dtikki=doubletikki*spin2;
 int cbur=cheesebur*spin3;
 int gbur=grilledbur*spin4;
 int cpi=cheesepi*spin5;
 int tpi=tomatopi*spin6;
 int spi=spegati*spin7;
 int opi=onionpi*spin8;
 int cok=cokes*spin9;
int fry=frie*spin10;
 int cak=cakes*spin11;
 int shak= shakes *spin12 ;  
         
  //displaying totals
  //burgers
  int burtotal=stikki+dtikki+cbur+gbur;
  burgertotal.setText(" "+burtotal);
   
  //pizzas
int pizatotal=cpi+tpi+spi+opi;
  pizzatotal.setText(" "+pizatotal);
    
//drinks and others
int otherstotal=cok+fry+cak+shak;
  drinkstotal.setText(" "+otherstotal);
  
 //total amount
 int totalamt=burtotal+pizatotal+otherstotal;
total.setText(" "+totalamt); 

//GST Charges
int gsttax=totalamt*8/100;
gst.setText(""+gsttax);

//Home deliery service charges
if(homedelivery.isSelected())
{totalamt=totalamt+30;
}
//Grand total
int gtotal=totalamt+gsttax;
grandtotal.setText(" "+gtotal);

  
  
  
      } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
    } 
 
 
      
     
        
                
                
    }//GEN-LAST:event_calculate_bill_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        grandtotal.setText(" ");
        drinkstotal.setText(" ");
        burgertotal.setText(" ");
         pizzatotal.setText(" ");
         total.setText(" "); 
         gst.setText(" ");
         bill.setText(" ");
         homedelivery.setSelected(false);
    }//GEN-LAST:event_clear_btnActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Welcomepage().setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null," YOU HAVE BEEN LOGGED OUT \n KINDLY LOGIN AGAIN");
    }//GEN-LAST:event_backMouseClicked

    private void place_order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_order_btnActionPerformed
         try {
        Statement st=new Connect().createConnection();
      ResultSet rs=st.executeQuery("select * FROM MENU");
      rs.next();
      int singletikki=rs.getInt("SINGLETIKKI");
      int doubletikki=rs.getInt("DOUBLETIKKI");
      int cheesebur=rs.getInt("CHEESEBUR");
      int grilledbur=rs.getInt("GRILLEDBUR");
      int cheesepi=rs.getInt("CHEESEPI");
      int tomatopi=rs.getInt("TOMATOPI");
      int spegati=rs.getInt("SPEGATIPI");
      int onionpi=rs.getInt("ONIONPI");
      int cokes=rs.getInt("COKE");
      int frie=rs.getInt("FRIES");
      int cakes=rs.getInt("CAKE");
      int shakes=rs.getInt("SHAKE");
 
             //getting values from jspinners
 int spin1=Integer.parseInt(lb1.getText());
 int spin2=Integer.parseInt(lb2.getText());
 int spin3=Integer.parseInt(lb3.getText());
 int spin4=Integer.parseInt(lb4.getText());
 int spin5=Integer.parseInt(lb5.getText());
 int spin6=Integer.parseInt(lb6.getText());
 int spin7=Integer.parseInt(lb7.getText());
 int spin8=Integer.parseInt(lb8.getText());
 int spin9=Integer.parseInt(lb9.getText());
 int spin10=Integer.parseInt(lb10.getText());
 int spin11=Integer.parseInt(lb11.getText());
 int spin12=Integer.parseInt(lb12.getText());
 
 //calculating values
 
 int stikki=singletikki*spin1;
 int dtikki=doubletikki*spin2;
 int cbur=cheesebur*spin3;
 int gbur=grilledbur*spin4;
 int cpi=cheesepi*spin5;
 int tpi=tomatopi*spin6;
 int spi=spegati*spin7;
 int opi=onionpi*spin8;
 int cok=cokes*spin9;
int fry=frie*spin10;
 int cak=cakes*spin11;
 int shak= shakes *spin12 ;  
         
  int burtotal=stikki+dtikki+cbur+gbur;
   
 
int pizatotal=cpi+tpi+spi+opi;
    
int otherstotal=cok+fry+cak+shak;
  
 int totalamt=burtotal+pizatotal+otherstotal;

int gsttax=totalamt*8/100;
int home=30;
if(homedelivery.isSelected())
{
    totalamt=totalamt+30;
}
int gtotal=totalamt+gsttax;
int bil=Integer.parseInt(txt.getText());

if(homedelivery.isSelected()){
bill.append("       FAST RESTURANT SERVICE \n\n "+ "-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_\n\n"+"Order No. \t\t " +"PUP00"+ bil+"\n\nBurgers total \t\t " +   burtotal+"\n\nPizzas total \t\t " +""+pizatotal 
+"\n\nDrinks and others \t " +otherstotal+"\n\n GST Tax \t\t "+gsttax+"\n\n Home Delivery \t\t " +home+"\n\n Grand total \t\t " +gtotal+"\n\n-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_\n"+"\n      Thanks for Choosing Us");
JOptionPane.showMessageDialog(null,"ORDER HAS BEEN SUCESSFULLY PLACED \n Will be delivered to Registered Address very shortly ");
}
else{
bill.append("       FAST RESTURANT SERVICE \n\n "+ "-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_\n\n"+"Order No. \t\t " +"PUP00"+ bil+"\n\nBurgers total \t\t " +   burtotal+"\n\nPizzas total \t\t " +""+pizatotal 
+"\n\nDrinks and others \t " +otherstotal+"\n\n GST Tax \t\t "+gsttax+"\n\n Grand total \t\t " +gtotal+"\n\n-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_\n"+"\n      Thanks for Choosing Us");
JOptionPane.showMessageDialog(null,"ORDER HAS BEEN SUCESSFULLY PLACED \n Your food is being prepared ");
} 
         } catch (SQLException ex) {
            Logger.getLogger(changeprice.class.getName()).log(Level.SEVERE, null, ex);
    }      
       bill(); 
    }//GEN-LAST:event_place_order_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
       Class.forName("org.apache.derby.jdbc.ClientDriver");
       Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/RESTAURANT","ankit","ankit");
       PreparedStatement pst=con.prepareStatement("select * from INVOICE");
       ResultSet rs=pst.executeQuery();
       rs.next();
       String j=rs.getString("ID");
       txt.setText(""+j);
       
      }
       catch(Exception e){
           System.out.println("error ");
       
       
       }

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel back;
    private javax.swing.JTextArea bill;
    private javax.swing.JLabel burgertotal;
    private javax.swing.JButton calculate_bill_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel drinkstotal;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel gst;
    private javax.swing.JCheckBox homedelivery;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb15;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel pizzatotal;
    private javax.swing.JButton place_order_btn;
    private javax.swing.JLabel total;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
